version: "3.2"

services:
  configuration-api:
    image: configuration-api
    build:
      context: ConfigurationApi/
      dockerfile: ./Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000   
    links:
      - localstack-configuration-api
  
  configuration-api-test:
    image: configuration-api-test
    environment:
      - CONFIGURATION_S3_BUCKETNAME=configuration-api-configurations
      - CONFIGURATION_S3_URL=http://localstack-configuration-api:4566
    build:
      context: .
      dockerfile: ConfigurationApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}    
      - SONAR_TOKEN=${SONAR_TOKEN}
    links:
      - localstack-configuration-api
      
  localstack-configuration-api:
    container_name: localstack-configuration-api
    image: localstack/localstack    
    hostname: awslocal    
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
