version: "3.2"

services:
  configuration-api:
    image: configuration-api
    build:
      context: ConfigurationApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  
  configuration-api-test:
    image: configuration-api-test
    build:
      context: .
      dockerfile: ConfigurationApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - localstack
      
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack    
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=s3
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"