version: "3.2"

services:
  configuration-api:
    image: configuration-api
    build:
      context: ConfigurationApi/
      dockerfile: ./Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
  
  configuration-api-test:
    image: configuration-api-test
    environment:
      - CONFIGURATION_S3_BUCKETNAME=http://localstack:4566
    build:
      context: .
      dockerfile: ConfigurationApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}    
    links:
      - localstack
      
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack    
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=s3:4566
      - DEFAULT_REGION=eu-west-2
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"