version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  docker-python:
    docker:
      - image: cimg/python:3.12
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-apply:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve
  terraform-preview:
    description: "Gives a preview for Terraform configuration changes."
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
            terraform plan
          name: terraform preview
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./ConfigurationApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./ConfigurationApi/
            npm i serverless-associate-waf
            npm i @serverless/safeguards-plugin --save-dev
            sls deploy --stage <<parameters.stage>> --conceal

jobs:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  terraform-init-and-apply-to-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-init-then-apply:
          environment: "production"
  preview-disaster-recovery-terraform:
    executor: docker-terraform
    steps:
      - terraform-preview:
          environment: "production"
  deploy-to-disaster-recovery:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

workflows:
  disaster-recovery:
      jobs:
      - assume-role-disaster-recovery:
          context: api-assume-role-disaster-recovery-context
      - terraform-init-and-apply-to-disaster-recovery:
          requires:
            - assume-role-disaster-recovery
      - permit-disaster-recovery-release:
          type: approval
          requires:
            - terraform-init-and-apply-to-disaster-recovery
      - deploy-to-disaster-recovery:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - permit-disaster-recovery-release   
